repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^tests/fixtures/
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-coding==1.3.2
          - flake8-copyright==0.2.4
          - flake8-debugger==4.1.2
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        exclude: ^http_service/
        args:
          - --convention=google
          # Ignoring warnings about missing docstrings.
          - --add-ignore=D100,D101,D102,D103,D104,D105,D107
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: trailing-whitespace
        exclude: ^tests/test_repository.py
      - id: check-yaml
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--django"]
      - id: check-json
        exclude: ^tests/fixtures/
      - id: requirements-txt-fixer
      - id: check-vcs-permalinks
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude_types: [json]
  - repo: https://github.com/marco-c/taskcluster_yml_validator
    rev: v0.0.10
    hooks:
      - id: taskcluster_yml
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa

  - repo: meta
    hooks:
      - id: check-useless-excludes
default_language_version:
  python: python3
